name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - run: flutter pub get

    - run: flutter config --enable-web

    - run: |
        flutter build web --release \
          --dart-define=API_KEY=${{ secrets.FIREBASE_API_KEY }} \
          --dart-define=AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} \
          --dart-define=PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
          --dart-define=STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
          --dart-define=MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
          --dart-define=APP_ID=${{ secrets.FIREBASE_APP_ID }}

    - name: Archive Production Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web

  deploy_web:
    name: Deploy Web to Firebase Hosting
    needs: build_web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: build/web

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:ablokhin
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
