name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Build Flutter Web App
      run: |
        flutter pub get
        flutter build web --release --dart-define=API_KEY=${{ secrets.API_KEY }} --dart-define=AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} --dart-define=PROJECT_ID=${{ secrets.PROJECT_ID }} --dart-define=STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }} --dart-define=MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} --dart-define=APP_ID=${{ secrets.APP_ID }}

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --token "$FIREBASE_TOKEN"
